### ISSUE TITLE
PHP Momryfin

### ISSUE THREAD

**Issue by djoh2** [pe7er/mod_db8kivateam#1]

**Comment by djoh2** [comment]
Hi -- I have just updated to PHP 8.0 and the Kiva plugin is failing due to Call to undefined function money_format(). Is it possible to provide a fix? I really love this little plug in which updates our group totals on Kiva for our website. Thx.

**Comment by pe7er** [comment]
@djoh2 Thank you for your bug report.

I've checked the code and could not find any reference to ``money_format()``.

Could you please describe the steps that triggered the issue?

I found another issue with the photos on the loans page that I corrected in version 1.2.0: https://github.com/pe7er/mod_db8kivateam/blob/master/downloads/mod_db8kivateam-j3-v1.2.0.zip

**Comment by djoh2** [comment]
Thank you -- I've realised an old employee altered the code, using money_format() to render the Amount Loaned in the format $x,xxx.xx  But that's now deprecated in PHP8, so I have removed it. thanks!

**Comment by pe7er** [comment]
Thanks for reporting back so quickly.

I'm closing this issue...
